#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Zaw
source "${ZDOTDIR:-$HOME}/.zsh/zaw/zaw.zsh"
zstyle ':filter-select' max-lines 4 # use $LINES - 4 for filter-select
zstyle ':filter-select' case-insensitive yes # enable case-insensitive search
bindkey '^R' zaw-history
bindkey -M filterselect '^R' down-line-or-history
bindkey -M filterselect '^S' up-line-or-history
bindkey -M filterselect '^E' accept-search
bindkey '^P' zaw-process
bindkey '^F' zaw-open-file

#Aliases
alias tmux="tmux -2 attach"
alias bower='noglob bower'
alias down="aria2c --conf-path=${HOME}/.aria2/aria2.conf"
alias tdown="aria2c --all-proxy=http://127.0.0.1:8123 --conf-path=${HOME}/.aria2/aria2.conf"
alias fly='~/src/sshuttle/sshuttle  --dns -r 52565751e0b8cd99d30001ba@private-psamim.rhcloud.com 0/0 --exclude-from ~/src/sshuttle/excludes'
alias 'tyoutube'='torify youtube-dl'

# Pacman
 alias pacupg='sudo pacman -Syu'        # Synchronize with repositories and then upgrade packages that are out of date on the local system.
 alias pacins='sudo pacman -S'           # Install specific package(s) from the repositories
 alias pacrem='sudo pacman -Rns'        # Remove the specified package(s), its configuration(s) and unneeded dependencies
 alias pacinf='pacman -Si'              # Display information about a given package in the repositories
 alias pacsearch='pacman -Ss'             # Search for package(s) in the repositories

PATH="`ruby -e 'puts Gem.user_dir'`/bin:$PATH"
PATH="/home/samim/.cabal/bin:$PATH"
