#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...
export EDITOR=vim
alias ack=ack-grep

# Zaw
source "${ZDOTDIR:-$HOME}/.zsh/zaw/zaw.zsh"
zstyle ':filter-select' max-lines 4 # use $LINES - 4 for filter-select
zstyle ':filter-select' case-insensitive yes # enable case-insensitive search
bindkey '^R' zaw-history
bindkey '^P' zaw-process
bindkey '^F' zaw-open-file

